"""Vendored (generated) copies of pure repo-toolkit modules.

Every file here except this ``__init__.py`` and ``README.md`` is a byte-identical
copy of a canonical module in the repo toolkit, generated by
``automation/vendoring/sync_vendored.py``. Do not edit the copies — edit the
canonical source and re-run the sync. See ``README.md`` in this folder.
"""
