"""gardener routine: compact the agent-state logs (search-log prune + log rebuild).

Two working-memory logs (AGENTS.md "Memory Map" zone (d)) grow without bound:

  * ``company-search-log.yaml`` — one row per employer's last successful search.
    Rows whose ``last_successful_search`` is older than ``search_log_prune_days``
    (default 90) are worth re-searching, so they are PRUNE candidates. On
    ``--apply`` a COMPACTED COPY is written BESIDE the original
    (``company-search-log.compacted.yaml``) for human review — the live file is
    never edited in place.
  * ``applications-log.yaml`` — a DERIVED index, self-bounding by construction. It
    is not pruned; it is REGENERATED by ``status.py --sync-log`` (idempotent). This
    routine only invokes that regeneration under ``--apply``.

DRY-RUN by default: prints the prune plan and the regeneration note; writes nothing.

Usage:
    .venv/bin/python automation/maintenance/gardener/compact_logs.py
    .venv/bin/python automation/maintenance/gardener/compact_logs.py --apply
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _common as C  # noqa: E402

try:
    import config  # noqa: E402
except ImportError:  # pragma: no cover
    config = C.config

STATUS_SCRIPT = (
    C.REPO_ROOT / "skills" / "application-tracker" / "scripts" / "status.py"
)


def _profile_dir() -> Path:
    return config.applications_root() / "0_profile"


def search_log_path() -> Path:
    return _profile_dir() / "company-search-log.yaml"


def plan(policy: dict) -> dict:
    """Return prune candidates for the company-search-log."""
    import yaml
    path = search_log_path()
    prune_days = policy["search_log_prune_days"]
    ref = C.today()
    keep: list[dict] = []
    prune: list[dict] = []
    data: dict = {}
    if path.is_file():
        data = yaml.safe_load(path.read_text()) or {}
        for row in data.get("companies") or []:
            d = C.parse_iso(str(row.get("last_successful_search") or "")[:10])
            age = (ref - d).days if d else None
            if age is not None and age > prune_days:
                prune.append({"name": row.get("name"), "date": d.isoformat(), "age": age})
            else:
                keep.append(row)
    return {"path": path, "data": data, "keep": keep, "prune": prune,
            "prune_days": prune_days}


def run(apply: bool = False) -> int:
    policy = C.retention()
    C.print_header("compact-logs", apply)
    try:
        p = plan(policy)
    except ImportError:
        print("  pyyaml unavailable — cannot parse the search log.", file=sys.stderr)
        return 1

    path = p["path"]
    print(f"  search-log: {C.rel(path)}  (prune rows older than {p['prune_days']}d)")
    if not path.is_file():
        print("  search-log not found — nothing to prune.")
    else:
        print(f"  PRUNE candidates: {len(p['prune'])} of "
              f"{len(p['prune']) + len(p['keep'])} rows")
        for r in p["prune"]:
            print(f"    prune  {r['name']}  (last search {r['date']}, {r['age']}d)")

    print(f"\n  applications-log: {C.rel(_profile_dir() / 'applications-log.yaml')}")
    print("    DERIVED / regenerable — not pruned; rebuilt by "
          "status.py --sync-log (idempotent).")

    if not apply:
        print("\n  DRY-RUN: no files written. --apply writes "
              "company-search-log.compacted.yaml and runs status.py --sync-log.")
        return 0

    # --apply: write the compacted copy BESIDE the original (never in place).
    if p["prune"]:
        import yaml
        out = path.with_name("company-search-log.compacted.yaml")
        compacted = dict(p["data"])
        compacted["companies"] = p["keep"]
        header = (
            "# gardener compact-logs preview — REVIEW BEFORE REPLACING THE LIVE LOG.\n"
            f"# Pruned {len(p['prune'])} row(s) with last search older than "
            f"{p['prune_days']}d ({C.DESIGN_DOC}).\n"
            "# The live company-search-log.yaml was NOT modified.\n\n"
        )
        out.write_text(header + yaml.safe_dump(compacted, sort_keys=False,
                                               allow_unicode=True), encoding="utf-8")
        print(f"\n  APPLY: wrote {C.rel(out)} ({len(p['keep'])} rows kept). "
              "Review, then replace the live log yourself.")
    else:
        print("\n  APPLY: no prune candidates — no compacted copy written.")

    # Regenerate the derived applications-log via the idempotent status.py sync.
    if STATUS_SCRIPT.is_file():
        print("  APPLY: regenerating applications-log via status.py --sync-log ...")
        r = subprocess.run([sys.executable, str(STATUS_SCRIPT), "--sync-log"])
        if r.returncode != 0:
            print("  WARN: status.py --sync-log exited non-zero.", file=sys.stderr)
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--apply", action="store_true",
                    help="write the compacted copy + run status.py --sync-log")
    return run(ap.parse_args(argv).apply)


if __name__ == "__main__":
    raise SystemExit(main())
